name: Discord Notification

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Notification
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: |
          ${{ github.event_name == 'issues' && (github.event.action == 'opened' && 'New issue opened:' || 'Issue closed:') || 'Pull request ' }}${{ github.event.action == 'closed' && 'closed:' || (github.event_name == 'pull_request' && 'opened:') }}
          
          **Title:** ${{ github.event.issue.title || github.event.pull_request.title }}
          **URL:** ${{ github.event.issue.html_url || github.event.pull_request.html_url }}
          **User:** ${{ github.event.issue.user.login || github.event.pull_request.user.login }}
          
          ${{ github.event.issue.body || github.event.pull_request.body }}
