name: Discord Notification for Issues

on:
  issues:
    types: [opened, closed]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Notification
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub"
        message: |
          ${{ format('{0}', github.event.action == 'opened' && 'New issue opened:' || 'Issue closed:') }}

          **${{ github.event.issue.title }}**
          ${{ github.event.issue.html_url }}
          by ${{ github.event.issue.user.login }}
